JC = javac
JFLAGS = -classpath .
JD = javadoc
JDFLAGS = -protected -splitindex -use -author -version -d ./javadoc
RM = rm
JR = java

CLASSES = \
		Inventory.java \
		Device.java \
		Driver.java \
		SmartPhone.java \
		Computer.java \
		VacuumCleaner.java \
		TV.java \
		Headphones.java \

all : Driver.class

run : 
	$(JR) Driver

classes : $(CLASSES:.java=.class)

%.class : %.java
	$(JC) $(JFLAGS) $<

doc:
	$(JD) $(JDFLAGS) *.java 

clean:
	$(RM) *.class 

cleandoc:
	$(RM) -r ./javadoc